absl-py==1.4.0
accelerate==0.18.0
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
altair==4.2.2
anyio==3.6.2
astunparse==1.6.3
async-timeout==4.0.2
asynctest==0.13.0
attrs==22.2.0
bitsandbytes==0.31.7
braceexpand==0.1.7
cachetools==5.3.0
click==8.1.3
clip==1.0
cycler==0.11.0
entrypoints==0.4
fairscale==0.4.4
faiss==1.5.3
faiss-gpu==1.7.2
fastapi==0.95.1
ffmpy==0.3.0
filelock==3.9.0
flatbuffers==23.1.21
fonttools==4.38.0
frozenlist==1.3.3
fsspec==2023.1.0
ftfy==6.1.1
gast==0.4.0
google-auth==2.16.1
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
gradio==3.27.0
gradio-client==0.1.3
grpcio==1.51.1
h11==0.14.0
h5py==3.8.0
httpcore==0.17.0
httpx==0.24.0
huggingface-hub==0.13.4
importlib-metadata==6.0.0
importlib-resources==5.12.0
jinja2==3.1.2
joblib==1.2.0
jsonschema==4.17.3
keras==2.11.0
kiwisolver==1.4.4
libclang==15.0.6.1
lightning-utilities==0.8.0
linkify-it-py==2.0.0
markdown==3.4.1
markdown-it-py==2.2.0
markupsafe==2.1.2
matplotlib==3.5.3
mdit-py-plugins==0.3.3
mdurl==0.1.2
multidict==6.0.4
oauthlib==3.2.2
openai==0.27.0
opencv-python==4.7.0.68
opt-einsum==3.3.0
orjson==3.8.10
packaging==23.0
pandas==1.3.5
pickles==0.1.1
pkgutil-resolve-name==1.3.10
protobuf==3.19.6
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycocoevalcap==1.2
pycocotools==2.0.6
pydantic==1.10.7
pydub==0.25.1
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-multipart==0.0.6
pytorch-lightning==1.9.4
pytorch-metric-learning==2.0.0
pytorch-warmup==0.1.1
pytz==2022.7.1
pyyaml==6.0
regex==2022.10.31
requests-oauthlib==1.3.1
rsa==4.9
ruamel-yaml==0.17.21
ruamel-yaml-clib==0.2.7
sacremoses==0.0.53
safetensors==0.3.0
scann==1.2.9
scikit-learn==1.0.2
scipy==1.7.3
semantic-version==2.10.0
sklearn==0.0.post1
sniffio==1.3.0
sptag==1.6.1
starlette==0.26.1
tenacity==8.2.2
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.11.0
tensorflow-estimator==2.11.0
tensorflow-io-gcs-filesystem==0.30.0
termcolor==2.2.0
thop==0.1.1-2209072238
threadpoolctl==3.1.0
timm==0.4.12
tokenizers==0.13.3
toolz==0.12.0
torchmetrics==0.11.4
torchstat==0.0.7
torchsummary==1.5.1
tqdm==4.64.1
transformers==4.27.4
uc-micro-py==1.0.1
uvicorn==0.21.1
wcwidth==0.2.6
webdataset==0.2.48
websockets==11.0.1
werkzeug==2.2.3
wrapt==1.14.1
yarl==1.8.2
zipp==3.14.0

